version: '3.8'

services:
  api:
    container_name: api
    build: .
    tty: true
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
